### ISSUE TITLE
팔로우 시 상대 프로필 불러오기에 반영이 안되는 것 같음

### ISSUE THREAD

**Issue by gusah009** [KEEPER31337/Homepage-Back#217]
![image](https://user-images.githubusercontent.com/26597702/157806606-2353be7d-04af-41e0-8868-90a87b222f77.png)

**Comment by noonmap** [comment]
@gusah009 도대체 뭐지...? 단위 테스트에서는 조회 결과 잘 나오는데 postman에서는 이상하게 나오네요...
코드 다시봐도 왜 잘못 됐는지 모르겠 ㅠㅠ 어요 ㅠㅠㅠㅠㅠ 왜 버그나.... ㅠㅠㅠ 왜 내 눈엔 안 보여 ㅠㅠㅠ
나중에 다시 보겠습니다 다른 사람 시야가 필요해요 8ㅅ8

**Comment by gusah009** [comment]
@noonmap 나중에 한번 확인해보겠습니다!!
