### ISSUE TITLE
세미나 자동 출석 - API 개발 + 성공 테스트 케이스 작성 + API 문서화

### ISSUE THREAD

**Issue by gusah009** [KEEPER31337/Homepage-Back#359]

**Comment by shkisme** [comment]
### 회장

- [ ] 가장 최근의 세미나 ID, 이름 조회
- [ ] 출석 조건 조회(출석코드, 출석인정시간, 지각인정 시간 조회)
- [ ] 회장은 출석 조건 조회와 동시에 출석으로 인정

### 회원

- [ ] 가장 최근의 세미나 ID 조회
- [ ] 출석 확인(출결 종류, 출석코드 일치여부 조회)
- [ ] 출석 상태에 따른 상벌점 부여

**Comment by shkisme** [comment]
### 관리자

1. 가장 최근의 세미나 ID, 이름 조회 API

2. 출석 코드 생성 API

** 회장은 출석 코드 생성과 동시에 출석으로 인정

** 출석 체크가 종료되면, 출석 이전 상태의 회원을 결석으로 처리 + 벌점 부여 + 상벌점 내역(결석)으로 추가

### 회원

1. 가장 최근의 세미나 ID 조회 API

2. 출석 확인 API

** 지각 짝수 횟수, 무단 결석 + 상벌점 내역(지각,결석)으로 추가 -> 벌점 부여
